export const migrationPanels = [
  { name: 'Жалюзи' },
  { name: 'Кассиопея', shirt: '10 мм.' },
  { name: 'Мария' },
  { name: 'Милан' },
  { name: 'Плоская' },
  { name: 'Буазери' },
  { name: 'Рубашка 1.5мм', shirt: '1.5 мм' },
  { name: 'Рубашка 4мм', shirt: '4 мм' },
  { name: 'Рубашка буазери', shirt: '1.5 мм' },
  { name: 'Афина', shirt: '1.5 мм' },
  { name: 'Стандарт' },
  { name: 'Тиффани', shirt: '4 мм' },
  { name: 'Фигурная' },
  { name: 'Флора' },
  { name: 'Нео-Классика', shirt: '8 мм' },
  { name: 'Нео Берта с цв.' },
  { name: 'Венетто' },
  { name: 'Скалли', shirt: '4 мм' },
  { name: 'Париж' },
];

export const migrationShirts = [
  {
    name: '10 мм.',
    depthOverlay: null,
    figoreaSize: null,
    indent: null,
    works: [1],
  },
  {
    name: '1.5 мм',
    depthOverlay: 1.5,
    figoreaSize: 101,
    indent: null,
    works: [1],
  },
  { name: '4 мм', depthOverlay: 4, figoreaSize: 40, indent: null, works: [1] },
  { name: '8 мм', depthOverlay: 8, figoreaSize: 80, indent: null, works: [1] },
];
