

export const migrationSectors = [
  { name: 'Шлифовка', orderBy: 11 },
  { name: 'Сборка', orderBy: 4 },
  { name: 'ЧПУ', orderBy: 5 },
  { name: 'Отделка (первый этап)', orderBy: 12 },
  { name: 'Упаковка', orderBy: 16 },
  { name: 'Колеровка', orderBy: 6 },
  { name: 'Раскрой Шпона', orderBy: 1 },
  { name: 'Раскрой МДФ', orderBy: 2 },
  { name: 'Лакировка №2', orderBy: 12 },
  { name: 'Лакировка №3', orderBy: 12 },
  { name: 'Шлифовка Патины', orderBy: 13 },
  { name: 'Лак', orderBy: 14 },
  { name: 'Офис', orderBy: 0 },
  { name: 'Гость', orderBy: 0 },
  { name: 'Изготовление заготовки', orderBy: 7 },
  { name: 'Изготовление лестниц', orderBy: 22 },
  { name: 'Сборка сложных', orderBy: 8 },
  { name: 'Сборка мебели', orderBy: 15 },
  { name: 'Приклейка шпона', orderBy: 3 },
  { name: 'Склад декора', orderBy: 9 },
  { name: 'Шлифовка Станок', orderBy: 11 },
  { name: 'Склад упакованных заказов', orderBy: 20 },
  { name: 'Отгрузка', orderBy: 21 },
  { name: 'Шлифовка филёнок', orderBy: 12 },
  { name: 'Шлифовка Нижний Цех', orderBy: 11 },
];